services:
  bio1server:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: docker/server.Dockerfile
      args:
        - SERVER_PATH=./bioserv1/bioserver
        - RUN_FILE_PATH=./bioserv1/run_file1.sh
    environment:
      - SERVER_IP=${SERVER_IP}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=localhost
      - JAVA_DB_PARAMS=${JAVA_DB_PARAMS}
    env_file:
      - .env
    network_mode: "host"